= Monty Hall game show simulation

image:goat.svg[Goat,200]

You are on a game show where you are given the choice of three doors.
Behind one door is a car.
Behind the other doors are goats.
You pick a door and the host always opens a different door that reveals a goat, never the car.
The host then asks you if you would like to stay with your original choice or choose a different door.

Is it to your advantage to switch your choice of doors?

The https://en.wikipedia.org/wiki/Monty_Hall_problem[Monty Hall problem] is named after a popular game show host.

== Play the game

https://timothypratley.github.io/montyhall

== Solution

https://en.wikipedia.org/wiki/Marilyn_vos_Savant::[Marilyn vos Savant] has the highest recorded intelligence quotient (IQ) in the Guinness Book of Records.
Marilyn correctly answered yes, you are twice as likely to win if you switch rather than stay.
She went on to explain why, using a table of outcomes when you choose door #1.

Staying wins 1/3 of the time.
Swapping wins 2/3 of the time.

== Contributing

Pull requests welcome.

See link:Makefile[] setup/build/deploy tasks.
